; PlatformIO - Dual Sensor Monitoring
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM13
monitor_port = COM13
lib_deps = 
    adafruit/DHT sensor library@^1.4.4
